apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: posts
spec:
  rules:
    - host: posts-dhbw-exercise-1.2886795283-80-kota02.environments.katacoda.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: posts
              servicePort: 4000
